GET http://localhost:8085/therapistes
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTcxNTgwMjU3MiwiaWF0IjoxNzE1ODAxOTcyLCJzY29wZSI6IlJPTEVfQWRtaW4ifQ.eBFCyXIeRKK9J5nypUL9QwHhlSntQSCjP_ZqK1_ySPnqjYEj2g9D0Ff-Mp4MABEMuFsZwMyTKNRSgHKlPRJxtA
###
POST http://localhost:8085/auth/login
Content-Type: application/x-www-form-urlencoded

username=Adham&password=Adham1234
###
POST http://localhost:8085/sessions/Adham/8/mysession
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBZGhhbSIsImV4cCI6MTcxNjkzMDk0NSwiaWF0IjoxNzE2OTMwMzQ1LCJzY29wZSI6IlJPTEVfUGF0aWVudCJ9.yKpMVk8t2yUVtSx7nlN7eS4D0xdPBCF2mLcOwK9aSfIoVTACI9j9BDJ_A_jfWV_0wuwRJz5haWfGGV1LSagSLA

{
  "nameSession": "session2",
  "DateSession": "2021-03-25 00:00:00"
}
###
POST http://localhost:8085/auth/signup
Content-Type: application/json

{
    "userName": "toto",
    "email": "toto@gmail.com",
    "password": "toto1234",
    "phone": "0610345688",
    "gender": "Female",
    "age": 25,
    "city": "Casablanca",
    "profession": "Student",
    "medicalHistory": "psycho",
    "role": "patient"

}

###
GET http://localhost:8085/auth/profile
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTcxNTc5MDIxOSwiaWF0IjoxNzE1Nzg5NjE5LCJzY29wZSI6IlJPTEVfQWRtaW4ifQ.lyGPg0UA6FMsOnEflBHMDB9xQoz0Pt-vEa1618XUXTdqznbysVdAwfmiWJP0mWrcTD5NiaEIKKLkffN061vG6Q
###
POST  http://localhost:8085/patients
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTcxNTQ3NzI2MSwiaWF0IjoxNzE1NDc2NjYxLCJzY29wZSI6IlJPTEVfQWRtaW4ifQ.KeyWMk6c231Fhg-Dvw_VMCtGiHwGLWx7jno9wH4nMIO-C4SjsmjuPKk-sgmuSRmTrW4oHzYjA7QFUKVao9_Tbw

{
    "userName": "said",
    "email": "said@gmail.com",
    "password": "said1234",
    "phone": "0612345678",
    "gender": "Male",
    "age": 25,
    "city": "Casablanca",
    "profession": "Engineer",
    "medicalHistory": "psycho"

}
###
POST http://localhost:8085/patient_post
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBZGhhbSIsImV4cCI6MTcxNjQwNDAwNywiaWF0IjoxNzE2NDAzNDA3LCJzY29wZSI6IlJPTEVfUGF0aWVudCJ9.jYNL-SOle21tldiDoUsP8zs8IoDHiUHdCBfjKadZDUsUnKgr4YHV6zcNBlMlJ6vqPCrfaHYIS6c-XIHy1_9c_Q

{
    "title": "new post",
    "content": "new content"

}

###
GET http://localhost:8085/posts

###
GET http://localhost:8085/notes/patient/Adham
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBZGhhbSIsImV4cCI6MTcxNjQwMzM3MywiaWF0IjoxNzE2NDAyNzczLCJzY29wZSI6IlJPTEVfUGF0aWVudCJ9.mZpb_cv4SL-XLLsHhOqYR05jFIg9Af2aqe1w9p3lr__DCRB4gxhaEUBjtZcb7kK3hVBlJntdlAAcvDiORRSlng
###
POST http://localhost:8085/patient_note
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBZGhhbSIsImV4cCI6MTcxNjQwNDAwNywiaWF0IjoxNzE2NDAzNDA3LCJzY29wZSI6IlJPTEVfUGF0aWVudCJ9.jYNL-SOle21tldiDoUsP8zs8IoDHiUHdCBfjKadZDUsUnKgr4YHV6zcNBlMlJ6vqPCrfaHYIS6c-XIHy1_9c_Q

    {
        "title": "new note",
        "content": "new content"

    }
###
DELETE http://localhost:8085/notes/user/
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBZGhhbSIsImV4cCI6MTcxNjQwNTQzMCwiaWF0IjoxNzE2NDA0ODMwLCJzY29wZSI6IlJPTEVfUGF0aWVudCJ9.1xQPG8rL4788WDCdUUiapOLd3kup_juYMXLsITgsQWOzmtL2RVX3Ca94iBzl6vl5WxOxP6l7WTXvyQcHpobTpQ

###
PATCH http://localhost:8085/notes/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBZGhhbSIsImV4cCI6MTcxNjQ4NDA5MiwiaWF0IjoxNzE2NDgzNDkyLCJzY29wZSI6IlJPTEVfUGF0aWVudCJ9.b1mmmCjS6jGP7UQtKSULCGq3RSH__keyE7ikV1IT_gMIQdfY6n8dtci8YdK1HUNhLNTMakbbTOqbs7rFt-I0pA

    {
        "title": "new note",
        "content": "new content"

    }
###
POST http://localhost:8085/therapistes
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTcxNjczMjIxNCwiaWF0IjoxNzE2NzMxNjE0LCJzY29wZSI6IlJPTEVfQWRtaW4ifQ.cyQrSq3k6_SBuBnevTCQfYZJ2kn34INt__1AjHQ9cUYRZW20aOV-Wr5C5egSrhMqPrCqVKMpLxibjBghVrZtzg

{
    "userName": "simohamed",
    "email": "simo99@gmail.com",
    "password": "simohamed1234",
  "phone": "0612341012",
  "gender": "Male",
  "therapistRole": "Pedopsychiatre",
  "price": 200,
  "localAddress": "Tanger",
  "aviability": true
}
